### ISSUE TITLE
Activity Message of FishBot shown in all servers

### ISSUE THREAD

**Issue by pedall** [FishyFing/FishBot#3]
I would love to have Fishbot not to show the activities of other servers in its status message, but only the activities of my own server.

At the moment i see all activities of the Bot of the MonsterLyrics server. E.g. someone is playing music.

![image](https://cloud.githubusercontent.com/assets/20089354/16265955/8a3f8590-3882-11e6-8299-9db146736158.png)

![image](https://cloud.githubusercontent.com/assets/20089354/16265962/98d85096-3882-11e6-8ce3-ee6cb188a1cd.png)

**Comment by marcorennmaus** [comment]
I don't think that's actually possible...
